PackageIdentifier: deafsquad.UpdateLoxone
PackageVersion: 0.9.3
InstallerLocale: en-US
InstallerType: msi
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/deafsquad/UpdateLoxone/releases/download/v0.9.3/UpdateLoxone-v0.9.3.msi
    InstallerSha256: 4144FA03A2F60FE5F907E778FAA6281C9EF29CDBE6C4B6B5E82DC83EC9AED040
    ProductCode: '{00000000-0000-0000-0000-000000000000}'
ManifestType: installer
ManifestVersion: 1.6.0
